In [ ]:
import torch
x = torch.tensor([3.], requires_grad=True)
x.grad

In [3]:
y = torch.exp(x)
y.backward()
x.grad

tensor([20.0855])

In [4]:
torch.exp(x)

tensor([20.0855], grad_fn=<ExpBackward0>)

In [5]:
x.grad -= x.grad
x.grad

tensor([0.])